package cn.it.bos.domain.zm;
// Generated 2017-1-8 9:56:43 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZmTransferinfo generated by hbm2java
 */
@Entity
@Table(name="zm_transferinfo"
    ,catalog="mavenbos"
)
public class ZmTransferinfo  implements java.io.Serializable {
	@Override
	public String toString() {
		return "ZmTransferinfo [id=" + id + ", zmZhongzhuaninfo=" + zmZhongzhuaninfo + ", info=" + info + ", arrive="
				+ arrive + ", updateTime=" + updateTime + ", index=" + index + "]";
	}

	private static final long serialVersionUID = 1L;

     private Long id;
     private ZmZhongzhuaninfo zmZhongzhuaninfo;
     private String info;
     private String arrive;
     private Date updateTime;
     private Integer index;

    public ZmTransferinfo() {
    }

	
    public ZmTransferinfo(Date updateTime) {
        this.updateTime = updateTime;
    }
    public ZmTransferinfo(ZmZhongzhuaninfo zmZhongzhuaninfo, String info, String arrive, Date updateTime, Integer index) {
       this.zmZhongzhuaninfo = zmZhongzhuaninfo;
       this.info = info;
       this.arrive = arrive;
       this.updateTime = updateTime;
       this.index = index;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zhongzhuaninfo_id")
    public ZmZhongzhuaninfo getZmZhongzhuaninfo() {
        return this.zmZhongzhuaninfo;
    }
    
    public void setZmZhongzhuaninfo(ZmZhongzhuaninfo zmZhongzhuaninfo) {
        this.zmZhongzhuaninfo = zmZhongzhuaninfo;
    }
    
    @Column(name="info")
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    
    @Column(name="arrive")
    public String getArrive() {
        return this.arrive;
    }
    
    public void setArrive(String arrive) {
        this.arrive = arrive;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updateTime", nullable=false, length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Column(name="index")
    public Integer getIndex() {
        return this.index;
    }
    
    public void setIndex(Integer index) {
        this.index = index;
    }




}


