package cn.it.bos.domain.zm;
// Generated 2017-1-8 9:56:43 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import cn.it.bos.domain.qp.WorkOrderManage;

/**
 * ZmZhongzhuaninfo generated by hbm2java
 */
@Entity
@Table(name="zm_zhongzhuaninfo"
    ,catalog="mavenbos"
)
public class ZmZhongzhuaninfo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
     @Override
	public String toString() {
		return "中转流程 {流程id=" + id + ", 出库信息=" + zmOutstore + ", 入库信息=" + zmInstore
				+ ", zmReceivegoodsinfo [" + zmReceivegoodsinfo + "], arrive="
				+ arrive + ", zmTransferinfos [" + zmTransferinfos + "], 工作单详情 [" + workordermanage + "] }";
	}

	private ZmOutstore zmOutstore;
     private ZmInstore zmInstore;
     private ZmReceivegoodsinfo zmReceivegoodsinfo;
     private WorkOrderManage workordermanage;
     private String arrive;
     private Set<ZmTransferinfo> zmTransferinfos = new HashSet<ZmTransferinfo>(0);

    public ZmZhongzhuaninfo() {
    }

    public ZmZhongzhuaninfo(ZmOutstore zmOutstore, ZmInstore zmInstore, ZmReceivegoodsinfo zmReceivegoodsinfo, WorkOrderManage workordermanage, String arrive, Set<ZmTransferinfo> zmTransferinfos) {
       this.zmOutstore = zmOutstore;
       this.zmInstore = zmInstore;
       this.zmReceivegoodsinfo = zmReceivegoodsinfo;
       this.workordermanage = workordermanage;
       this.arrive = arrive;
       this.zmTransferinfos = zmTransferinfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outstore_id")
    public ZmOutstore getZmOutstore() {
        return this.zmOutstore;
    }
    
    public void setZmOutstore(ZmOutstore zmOutstore) {
        this.zmOutstore = zmOutstore;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instore_id")
    public ZmInstore getZmInstore() {
        return this.zmInstore;
    }
    
    public void setZmInstore(ZmInstore zmInstore) {
        this.zmInstore = zmInstore;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="receivegoodsinfo_id")
    public ZmReceivegoodsinfo getZmReceivegoodsinfo() {
        return this.zmReceivegoodsinfo;
    }
    
    public void setZmReceivegoodsinfo(ZmReceivegoodsinfo zmReceivegoodsinfo) {
        this.zmReceivegoodsinfo = zmReceivegoodsinfo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="workOrderManage_id")
    public WorkOrderManage getWorkordermanage() {
        return this.workordermanage;
    }
    
    public void setWorkordermanage(WorkOrderManage workordermanage) {
        this.workordermanage = workordermanage;
    }
    
    @Column(name="arrive")
    public String getArrive() {
        return this.arrive;
    }
    
    public void setArrive(String arrive) {
        this.arrive = arrive;
    }
@OneToMany( fetch=FetchType.LAZY, mappedBy="zmZhongzhuaninfo")
    public Set<ZmTransferinfo> getZmTransferinfos() {
        return this.zmTransferinfos;
    }
    
    public void setZmTransferinfos(Set<ZmTransferinfo> zmTransferinfos) {
        this.zmTransferinfos = zmTransferinfos;
    }




}


