package cn.it.bos.domain.qp;
// Generated 2016-12-21 22:50:21 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import cn.it.bos.domain.bc.Staff;

/**
 * WorkBill generated by hbm2java
 */
@Entity
@Table(name="qp_workbill"
    ,catalog="mavenbos"
)
public class WorkBill  implements java.io.Serializable {

	@Override
	public String toString() {
		return "WorkBill [id=" + id + ", noticeBill=" + noticeBill + ", staff=" + staff + ", type=" + type
				+ ", pickstate=" + pickstate + ", buildtime=" + buildtime + ", attachbilltimes=" + attachbilltimes
				+ ", remark=" + remark + "]";
	}

	private static final long serialVersionUID = 1L;
     private String id;
     private NoticeBill noticeBill;
     private Staff staff;
     private String type;
     private String pickstate;
     private Date buildtime;
     private Integer attachbilltimes;
     private String remark;

    public WorkBill() {
    }

	
    public WorkBill(String id, Date buildtime) {
        this.id = id;
        this.buildtime = buildtime;
    }
    public WorkBill(String id, NoticeBill noticeBill, Staff staff, String type, String pickstate, Date buildtime, Integer attachbilltimes, String remark) {
       this.id = id;
       this.noticeBill = noticeBill;
       this.staff = staff;
       this.type = type;
       this.pickstate = pickstate;
       this.buildtime = buildtime;
       this.attachbilltimes = attachbilltimes;
       this.remark = remark;
    }
   
    @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="noticebill_id")
    public NoticeBill getNoticeBill() {
        return this.noticeBill;
    }
    
    public void setNoticeBill(NoticeBill noticeBill) {
        this.noticeBill = noticeBill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staff_id")
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    
    @Column(name="type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="pickstate", length=20)
    public String getPickstate() {
        return this.pickstate;
    }
    
    public void setPickstate(String pickstate) {
        this.pickstate = pickstate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buildtime", nullable=false, length=19)
    public Date getBuildtime() {
        return this.buildtime;
    }
    
    public void setBuildtime(Date buildtime) {
        this.buildtime = buildtime;
    }
    
    @Column(name="attachbilltimes")
    public Integer getAttachbilltimes() {
        return this.attachbilltimes;
    }
    
    public void setAttachbilltimes(Integer attachbilltimes) {
        this.attachbilltimes = attachbilltimes;
    }
    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


