package cn.it.bos.domain.qp;
// Generated 2016-12-21 22:50:21 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;
import org.wltea.analyzer.lucene.IKAnalyzer;

import cn.it.bos.domain.zm.ZmZhongzhuaninfo;

/**
 * WorkOrderManage generated by hbm2java
 */
@Entity
@Table(name="qp_workordermanage"
    ,catalog="mavenbos"
)
@Indexed
@Analyzer(impl=IKAnalyzer.class )
public class WorkOrderManage  implements java.io.Serializable {

	@Override
	public String toString() {
		return "WorkOrderManage [id=" + id + ", 工作单号=" + wid + ", 到达地=" + arrivecity + ", 产品=" + product
				+ ", 件数=" + num + ", 重量=" + weight + ", 配载要求=" + floadreqr + ", 产品时限="
				+ prodtimelimit + ", 产品类型=" + prodtype + ", 寄件人姓名=" + sendername + ", 寄件人电话="
				+ senderphone + ", 寄件人地址=" + senderaddr + ", 收货人名称=" + receivername + ", 收货人电话="
				+ receiverphone + ", 收货地址=" + receiveraddr + ", 计费件数（原件数）=" + feeitemnum + ", 实际重量="
				+ actlweit + ", 体积（尺寸）=" + vol + ", 核查 =" + managerCheck + ", 更新时间=" + updatetime
				+ ", zmZhongzhuaninfos=" + zmZhongzhuaninfos + "]";
	}

	private static final long serialVersionUID = 1L;
	 @DocumentId
     private String id;       		//uuid主键
	 @Field(store=Store.NO,index=Index.TOKENIZED)
     private String wid;       		//工作单号
	 @Field(store=Store.NO,index=Index.TOKENIZED)
     private String arrivecity;	 	//到达地
	 @Field(store=Store.NO,index=Index.TOKENIZED)
	 private String product;		//产品
     private Integer num;			//件数
     private Double weight;			//重量
     private String floadreqr;		//配载要求
     private String prodtimelimit;	//产品时限
     private String prodtype;		//产品类型
     private String sendername;		//寄件人姓名
     private String senderphone;	//寄件人电话
     private String senderaddr;		//寄件人地址
     private String receivername;	//收货人名称
     private String receiverphone;	//收货人电话
     private String receiveraddr;	//收货地址
     private Integer feeitemnum;	//计费件数（原件数）
     private Double actlweit;		//实际重量
     private String vol;			//体积（尺寸）
     private String managerCheck="0";	//核查 0 未审核, 1审核
     private Date updatetime;		//更新时间

     private Set<ZmZhongzhuaninfo> zmZhongzhuaninfos = new HashSet<ZmZhongzhuaninfo>(0);
     
    public WorkOrderManage() {
    }

	
    public WorkOrderManage(String id) {
        this.id = id;
    }
    @OneToMany( fetch=FetchType.LAZY, mappedBy="workordermanage")
    public Set<ZmZhongzhuaninfo> getZmZhongzhuaninfos() {
		return zmZhongzhuaninfos;
	}


	public void setZmZhongzhuaninfos(Set<ZmZhongzhuaninfo> zmZhongzhuaninfos) {
		this.zmZhongzhuaninfos = zmZhongzhuaninfos;
	}


	@GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="arrivecity", length=255)
    public String getArrivecity() {
        return this.arrivecity;
    }
    
    public void setArrivecity(String arrivecity) {
        this.arrivecity = arrivecity;
    }
    
    @Column(name="wid", length=20)
    public String getWid() {
        return this.wid;
    }
    
    public void setWid(String wid) {
        this.wid = wid;
    }
    
    @Column(name="product", length=255)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    
    @Column(name="num")
    public Integer getNum() {
        return this.num;
    }
    
    public void setNum(Integer num) {
        this.num = num;
    }
    
    @Column(name="weight", precision=22, scale=0)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    
    @Column(name="floadreqr",length=255)
    public String getFloadreqr() {
        return this.floadreqr;
    }
    
    public void setFloadreqr(String floadreqr) {
        this.floadreqr = floadreqr;
    }
    
    @Column(name="prodtimelimit", length=40)
    public String getProdtimelimit() {
        return this.prodtimelimit;
    }
    
    public void setProdtimelimit(String prodtimelimit) {
        this.prodtimelimit = prodtimelimit;
    }
    
    @Column(name="prodtype", length=40)
    public String getProdtype() {
        return this.prodtype;
    }
    
    public void setProdtype(String prodtype) {
        this.prodtype = prodtype;
    }
    
    @Column(name="sendername", length=20)
    public String getSendername() {
        return this.sendername;
    }
    
    public void setSendername(String sendername) {
        this.sendername = sendername;
    }
    
    @Column(name="senderphone", length=20)
    public String getSenderphone() {
        return this.senderphone;
    }
    
    public void setSenderphone(String senderphone) {
        this.senderphone = senderphone;
    }
    
    @Column(name="senderaddr", length=200)
    public String getSenderaddr() {
        return this.senderaddr;
    }
    
    public void setSenderaddr(String senderaddr) {
        this.senderaddr = senderaddr;
    }
    
    @Column(name="receivername", length=20)
    public String getReceivername() {
        return this.receivername;
    }
    
    public void setReceivername(String receivername) {
        this.receivername = receivername;
    }
    
    @Column(name="receiverphone", length=20)
    public String getReceiverphone() {
        return this.receiverphone;
    }
    
    public void setReceiverphone(String receiverphone) {
        this.receiverphone = receiverphone;
    }
    
    @Column(name="receiveraddr", length=200)
    public String getReceiveraddr() {
        return this.receiveraddr;
    }
    
    public void setReceiveraddr(String receiveraddr) {
        this.receiveraddr = receiveraddr;
    }
    
    @Column(name="feeitemnum")
    public Integer getFeeitemnum() {
        return this.feeitemnum;
    }
    
    public void setFeeitemnum(Integer feeitemnum) {
        this.feeitemnum = feeitemnum;
    }
    
    @Column(name="actlweit", precision=22, scale=0)
    public Double getActlweit() {
        return this.actlweit;
    }
    
    public void setActlweit(Double actlweit) {
        this.actlweit = actlweit;
    }
    
    @Column(name="vol", length=20)
    public String getVol() {
        return this.vol;
    }
    
    public void setVol(String vol) {
        this.vol = vol;
    }
    
    @Column(name="managerCheck", length=255)
    public String getManagerCheck() {
        return this.managerCheck;
    }
    
    public void setManagerCheck(String managerCheck) {
        this.managerCheck = managerCheck;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="updatetime", length=10)
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }




}


