package cn.it.crm.domain;
// Generated 2016-12-10 4:39:06 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="crm"
)
@SuppressWarnings("all")
public class Customer  implements java.io.Serializable {


     private String id;
     private String cname;
     private String tel;
     private String address;
     private String decidedzoneid;

    public Customer() {
    }

	
    public Customer(String id) {
        this.id = id;
    }
    public Customer(String id, String cname, String tel, String address, String decidedzoneid) {
       this.id = id;
       this.cname = cname;
       this.tel = tel;
       this.address = address;
       this.decidedzoneid = decidedzoneid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="cname", length=20)
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    
    @Column(name="tel", length=40)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="decidedzoneid", length=40)
    public String getDecidedzoneid() {
        return this.decidedzoneid;
    }
    
    public void setDecidedzoneid(String decidedzoneid) {
        this.decidedzoneid = decidedzoneid;
    }




}


