package cn.it.bos.domain.bc;
// Generated 2016-12-21 22:50:21 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DecidedZone generated by hbm2java
 */
@Entity
@Table(name="bc_decidedzone"
    ,catalog="mavenbos"
)
public class DecidedZone  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
     private Staff staff;
     private String name;
     private Set<Subarea> subareas = new HashSet<Subarea>(0);

    public DecidedZone() {
    }

	
    public DecidedZone(String id) {
        this.id = id;
    }
    public DecidedZone(String id, Staff staff, String name, Set<Subarea> subareas) {
       this.id = id;
       this.staff = staff;
       this.name = name;
       this.subareas = subareas;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staff_id")
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany( fetch=FetchType.LAZY, mappedBy="decidedZone")
    public Set<Subarea> getSubareas() {
        return this.subareas;
    }
    
    public void setSubareas(Set<Subarea> subareas) {
        this.subareas = subareas;
    }




}


